// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {app} from '../models';
import {plugin} from '../models';
import {media} from '../models';
import {agent} from '../models';
import {diff} from '../models';
import {llm} from '../models';
import {permission} from '../models';
import {skill} from '../models';
import {tool} from '../models';
import {snapshot} from '../models';
import {context} from '../models';

export function AddModel(arg1:store.Model):Promise<void>;

export function AddPermissionRule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AppendConversation(arg1:string,arg2:store.Conversation):Promise<void>;

export function AppendMessage(arg1:string,arg2:store.Message):Promise<store.Message>;

export function CancelAskUser(arg1:string):Promise<void>;

export function CancelPermissionWait(arg1:string):Promise<void>;

export function CancelPlan(arg1:string):Promise<void>;

export function Chat(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<app.ChatResult>;

export function ChatPlan(arg1:string,arg2:string,arg3:boolean):Promise<app.ChatResult>;

export function ClearPermissionGrants(arg1:string):Promise<void>;

export function ClearToolFileChanges(arg1:string):Promise<void>;

export function CompleteTask(arg1:string):Promise<void>;

export function CreateSession(arg1:store.SessionConfig):Promise<store.Session>;

export function CreateTask(arg1:plugin.TaskInput):Promise<plugin.TaskView>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteTask(arg1:string,arg2:boolean):Promise<void>;

export function DeleteTool(arg1:string):Promise<void>;

export function ExecutePlan(arg1:string,arg2:boolean):Promise<app.ChatResult>;

export function ExportMCPServers(arg1:Array<string>):Promise<string>;

export function FetchImageURL(arg1:string,arg2:string):Promise<media.Attachment>;

export function GetAttachmentDataURL(arg1:string,arg2:string):Promise<string>;

export function GetContextPrefs():Promise<store.ContextPrefs>;

export function GetContextStat(arg1:string):Promise<agent.ContextStat>;

export function GetDiff(arg1:string):Promise<Array<diff.DiffFile>>;

export function GetDiffTurns(arg1:string):Promise<Array<diff.DiffTurn>>;

export function GetLastLLMRequest(arg1:string):Promise<llm.RequestSnapshot>;

export function GetModel(arg1:string):Promise<store.Model>;

export function GetModelFull(arg1:string):Promise<store.Model>;

export function GetModelNames():Promise<Array<string>>;

export function GetModels():Promise<Array<store.Model>>;

export function GetPendingAsk(arg1:string):Promise<agent.AskRequest>;

export function GetPendingInteraction(arg1:string):Promise<app.PendingInteraction>;

export function GetPermissionAudit(arg1:string):Promise<Array<permission.AuditEntry>>;

export function GetPermissionState(arg1:string):Promise<app.PermissionState>;

export function GetPromptCachePrefs():Promise<store.PromptCachePrefs>;

export function GetSession(arg1:string):Promise<store.Session>;

export function GetSessionPlan(arg1:string):Promise<store.Plan>;

export function GetSkill(arg1:string):Promise<skill.SkillDetail>;

export function GetSubagentMessages(arg1:string):Promise<Array<store.Message>>;

export function GetTask(arg1:string):Promise<plugin.TaskView>;

export function GetTaskSettings():Promise<plugin.GlobalConfig>;

export function GetToolFileChanges(arg1:string):Promise<Array<tool.ToolFileChange>>;

export function GetUsageDetail(arg1:string):Promise<app.UsageDetail>;

export function Greet(arg1:string):Promise<string>;

export function ImportMCPServers(arg1:string):Promise<app.MCPImportResult>;

export function InstallSkillFromFolder(arg1:string):Promise<Array<skill.SkillInstallResult>>;

export function InstallSkillFromGit(arg1:string,arg2:string,arg3:string):Promise<Array<skill.SkillInstallResult>>;

export function InstallSkillFromZip(arg1:string):Promise<Array<skill.SkillInstallResult>>;

export function ListCheckpoints(arg1:string):Promise<Array<snapshot.CheckpointInfo>>;

export function ListPlans(arg1:string):Promise<Array<store.Plan>>;

export function ListRunningSessions():Promise<Array<string>>;

export function ListSessions():Promise<Array<store.Session>>;

export function ListSkillResources(arg1:string):Promise<Array<skill.SkillResource>>;

export function ListSkills():Promise<Array<skill.SkillMeta>>;

export function ListSubagents(arg1:string):Promise<Array<store.SubagentInfo>>;

export function ListTaskRuns(arg1:string,arg2:number):Promise<Array<plugin.RunRecord>>;

export function ListTasks():Promise<Array<plugin.TaskView>>;

export function ListTools():Promise<Array<tool.ToolInfo>>;

export function PauseAllTasks(arg1:boolean):Promise<void>;

export function PickDirectory():Promise<string>;

export function PickSkillFolder():Promise<string>;

export function PickSkillZip():Promise<string>;

export function PreviewTaskTriggerTimes(arg1:plugin.Trigger,arg2:number):Promise<Array<string>>;

export function RefreshSkills():Promise<Array<skill.SkillMeta>>;

export function RemovePermissionRule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ReopenPlan(arg1:string):Promise<store.Plan>;

export function ResolveAskUser(arg1:agent.AskAnswer):Promise<void>;

export function ResolvePermission(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RunTaskNow(arg1:string):Promise<plugin.RunRecord>;

export function SaveAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<media.Attachment>;

export function SavePlan(arg1:store.Plan):Promise<void>;

export function SaveSkill(arg1:string,arg2:skill.SkillDraft):Promise<void>;

export function SaveTool(arg1:tool.ToolSource):Promise<tool.ToolSource>;

export function SetContextKeepRecentMsgs(arg1:number):Promise<store.ContextPrefs>;

export function SetExposure(arg1:string,arg2:string):Promise<void>;

export function SetPromptCachePrefs(arg1:store.PromptCachePrefs):Promise<store.PromptCachePrefs>;

export function SetSessionPermissionMode(arg1:string,arg2:string):Promise<store.Session>;

export function SetSubToolEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetTaskEnabled(arg1:string,arg2:boolean):Promise<plugin.TaskView>;

export function SkillsDir():Promise<string>;

export function SnoozeTask(arg1:string,arg2:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopChat(arg1:string,arg2:boolean):Promise<boolean>;

export function TaskCounts():Promise<number|number>;

export function TaskPluginInfo():Promise<plugin.Info>;

export function TaskPluginManifest():Promise<plugin.Manifest>;

export function TestModelConnection(arg1:store.Model):Promise<void>;

export function TestToolConnection(arg1:tool.ToolSource):Promise<Array<tool.MCPToolMeta>>;

export function ToggleSkill(arg1:string,arg2:boolean):Promise<void>;

export function ToggleTool(arg1:string,arg2:boolean):Promise<void>;

export function UndoDiffTurn(arg1:string,arg2:number,arg3:boolean):Promise<snapshot.UndoResult>;

export function UpdateModel(arg1:string,arg2:store.Model):Promise<void>;

export function UpdateSession(arg1:string,arg2:store.SessionPatch):Promise<store.Session>;

export function UpdateSkill(arg1:string):Promise<skill.SkillInstallResult>;

export function UpdateTask(arg1:string,arg2:plugin.TaskInput):Promise<plugin.TaskView>;

export function UpdateTaskSettings(arg1:plugin.GlobalConfig):Promise<void>;
