// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1) {
  return window['go']['app']['App']['AddModel'](arg1);
}

export function AddPermissionRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddPermissionRule'](arg1, arg2, arg3, arg4);
}

export function AppendConversation(arg1, arg2) {
  return window['go']['app']['App']['AppendConversation'](arg1, arg2);
}

export function AppendMessage(arg1, arg2) {
  return window['go']['app']['App']['AppendMessage'](arg1, arg2);
}

export function CancelAskUser(arg1) {
  return window['go']['app']['App']['CancelAskUser'](arg1);
}

export function CancelPermissionWait(arg1) {
  return window['go']['app']['App']['CancelPermissionWait'](arg1);
}

export function CancelPlan(arg1) {
  return window['go']['app']['App']['CancelPlan'](arg1);
}

export function Chat(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Chat'](arg1, arg2, arg3, arg4);
}

export function ChatPlan(arg1, arg2, arg3) {
  return window['go']['app']['App']['ChatPlan'](arg1, arg2, arg3);
}

export function ClearPermissionGrants(arg1) {
  return window['go']['app']['App']['ClearPermissionGrants'](arg1);
}

export function ClearToolFileChanges(arg1) {
  return window['go']['app']['App']['ClearToolFileChanges'](arg1);
}

export function CompleteTask(arg1) {
  return window['go']['app']['App']['CompleteTask'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['app']['App']['CreateSession'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['app']['App']['CreateTask'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['app']['App']['DeleteModel'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['app']['App']['DeleteSkill'](arg1);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['app']['App']['DeleteTask'](arg1, arg2);
}

export function DeleteTool(arg1) {
  return window['go']['app']['App']['DeleteTool'](arg1);
}

export function ExecutePlan(arg1, arg2) {
  return window['go']['app']['App']['ExecutePlan'](arg1, arg2);
}

export function ExportMCPServers(arg1) {
  return window['go']['app']['App']['ExportMCPServers'](arg1);
}

export function FetchImageURL(arg1, arg2) {
  return window['go']['app']['App']['FetchImageURL'](arg1, arg2);
}

export function GetAttachmentDataURL(arg1, arg2) {
  return window['go']['app']['App']['GetAttachmentDataURL'](arg1, arg2);
}

export function GetContextPrefs() {
  return window['go']['app']['App']['GetContextPrefs']();
}

export function GetContextStat(arg1) {
  return window['go']['app']['App']['GetContextStat'](arg1);
}

export function GetDiff(arg1) {
  return window['go']['app']['App']['GetDiff'](arg1);
}

export function GetDiffTurns(arg1) {
  return window['go']['app']['App']['GetDiffTurns'](arg1);
}

export function GetLastLLMRequest(arg1) {
  return window['go']['app']['App']['GetLastLLMRequest'](arg1);
}

export function GetModel(arg1) {
  return window['go']['app']['App']['GetModel'](arg1);
}

export function GetModelFull(arg1) {
  return window['go']['app']['App']['GetModelFull'](arg1);
}

export function GetModelNames() {
  return window['go']['app']['App']['GetModelNames']();
}

export function GetModels() {
  return window['go']['app']['App']['GetModels']();
}

export function GetPendingAsk(arg1) {
  return window['go']['app']['App']['GetPendingAsk'](arg1);
}

export function GetPendingInteraction(arg1) {
  return window['go']['app']['App']['GetPendingInteraction'](arg1);
}

export function GetPermissionAudit(arg1) {
  return window['go']['app']['App']['GetPermissionAudit'](arg1);
}

export function GetPermissionState(arg1) {
  return window['go']['app']['App']['GetPermissionState'](arg1);
}

export function GetPromptCachePrefs() {
  return window['go']['app']['App']['GetPromptCachePrefs']();
}

export function GetSession(arg1) {
  return window['go']['app']['App']['GetSession'](arg1);
}

export function GetSessionPlan(arg1) {
  return window['go']['app']['App']['GetSessionPlan'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['app']['App']['GetSkill'](arg1);
}

export function GetSubagentMessages(arg1) {
  return window['go']['app']['App']['GetSubagentMessages'](arg1);
}

export function GetTask(arg1) {
  return window['go']['app']['App']['GetTask'](arg1);
}

export function GetTaskSettings() {
  return window['go']['app']['App']['GetTaskSettings']();
}

export function GetToolFileChanges(arg1) {
  return window['go']['app']['App']['GetToolFileChanges'](arg1);
}

export function GetUsageDetail(arg1) {
  return window['go']['app']['App']['GetUsageDetail'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ImportMCPServers(arg1) {
  return window['go']['app']['App']['ImportMCPServers'](arg1);
}

export function InstallSkillFromFolder(arg1) {
  return window['go']['app']['App']['InstallSkillFromFolder'](arg1);
}

export function InstallSkillFromGit(arg1, arg2, arg3) {
  return window['go']['app']['App']['InstallSkillFromGit'](arg1, arg2, arg3);
}

export function InstallSkillFromZip(arg1) {
  return window['go']['app']['App']['InstallSkillFromZip'](arg1);
}

export function ListCheckpoints(arg1) {
  return window['go']['app']['App']['ListCheckpoints'](arg1);
}

export function ListPlans(arg1) {
  return window['go']['app']['App']['ListPlans'](arg1);
}

export function ListRunningSessions() {
  return window['go']['app']['App']['ListRunningSessions']();
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function ListSkillResources(arg1) {
  return window['go']['app']['App']['ListSkillResources'](arg1);
}

export function ListSkills() {
  return window['go']['app']['App']['ListSkills']();
}

export function ListSubagents(arg1) {
  return window['go']['app']['App']['ListSubagents'](arg1);
}

export function ListTaskRuns(arg1, arg2) {
  return window['go']['app']['App']['ListTaskRuns'](arg1, arg2);
}

export function ListTasks() {
  return window['go']['app']['App']['ListTasks']();
}

export function ListTools() {
  return window['go']['app']['App']['ListTools']();
}

export function PauseAllTasks(arg1) {
  return window['go']['app']['App']['PauseAllTasks'](arg1);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function PickSkillFolder() {
  return window['go']['app']['App']['PickSkillFolder']();
}

export function PickSkillZip() {
  return window['go']['app']['App']['PickSkillZip']();
}

export function PreviewTaskTriggerTimes(arg1, arg2) {
  return window['go']['app']['App']['PreviewTaskTriggerTimes'](arg1, arg2);
}

export function RefreshSkills() {
  return window['go']['app']['App']['RefreshSkills']();
}

export function RemovePermissionRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RemovePermissionRule'](arg1, arg2, arg3, arg4);
}

export function ReopenPlan(arg1) {
  return window['go']['app']['App']['ReopenPlan'](arg1);
}

export function ResolveAskUser(arg1) {
  return window['go']['app']['App']['ResolveAskUser'](arg1);
}

export function ResolvePermission(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ResolvePermission'](arg1, arg2, arg3, arg4, arg5);
}

export function RunTaskNow(arg1) {
  return window['go']['app']['App']['RunTaskNow'](arg1);
}

export function SaveAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveAttachment'](arg1, arg2, arg3, arg4);
}

export function SavePlan(arg1) {
  return window['go']['app']['App']['SavePlan'](arg1);
}

export function SaveSkill(arg1, arg2) {
  return window['go']['app']['App']['SaveSkill'](arg1, arg2);
}

export function SaveTool(arg1) {
  return window['go']['app']['App']['SaveTool'](arg1);
}

export function SetContextKeepRecentMsgs(arg1) {
  return window['go']['app']['App']['SetContextKeepRecentMsgs'](arg1);
}

export function SetExposure(arg1, arg2) {
  return window['go']['app']['App']['SetExposure'](arg1, arg2);
}

export function SetPromptCachePrefs(arg1) {
  return window['go']['app']['App']['SetPromptCachePrefs'](arg1);
}

export function SetSessionPermissionMode(arg1, arg2) {
  return window['go']['app']['App']['SetSessionPermissionMode'](arg1, arg2);
}

export function SetSubToolEnabled(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetSubToolEnabled'](arg1, arg2, arg3);
}

export function SetTaskEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetTaskEnabled'](arg1, arg2);
}

export function SkillsDir() {
  return window['go']['app']['App']['SkillsDir']();
}

export function SnoozeTask(arg1, arg2) {
  return window['go']['app']['App']['SnoozeTask'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopChat(arg1, arg2) {
  return window['go']['app']['App']['StopChat'](arg1, arg2);
}

export function TaskCounts() {
  return window['go']['app']['App']['TaskCounts']();
}

export function TaskPluginInfo() {
  return window['go']['app']['App']['TaskPluginInfo']();
}

export function TaskPluginManifest() {
  return window['go']['app']['App']['TaskPluginManifest']();
}

export function TestModelConnection(arg1) {
  return window['go']['app']['App']['TestModelConnection'](arg1);
}

export function TestToolConnection(arg1) {
  return window['go']['app']['App']['TestToolConnection'](arg1);
}

export function ToggleSkill(arg1, arg2) {
  return window['go']['app']['App']['ToggleSkill'](arg1, arg2);
}

export function ToggleTool(arg1, arg2) {
  return window['go']['app']['App']['ToggleTool'](arg1, arg2);
}

export function UndoDiffTurn(arg1, arg2, arg3) {
  return window['go']['app']['App']['UndoDiffTurn'](arg1, arg2, arg3);
}

export function UpdateModel(arg1, arg2) {
  return window['go']['app']['App']['UpdateModel'](arg1, arg2);
}

export function UpdateSession(arg1, arg2) {
  return window['go']['app']['App']['UpdateSession'](arg1, arg2);
}

export function UpdateSkill(arg1) {
  return window['go']['app']['App']['UpdateSkill'](arg1);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['app']['App']['UpdateTask'](arg1, arg2);
}

export function UpdateTaskSettings(arg1) {
  return window['go']['app']['App']['UpdateTaskSettings'](arg1);
}
