/**
 * 工具图标白名单：显式引入 Lucide 图标保证 tree-shaking，
 * 配置中存储图标名（小写短横线），ToolIcon.vue 按名渲染
 */
import {
  Zap,
  Terminal,
  SquareTerminal,
  Blocks,
  Puzzle,
  Webhook,
  Globe,
  Cloud,
  Bot,
  FileText,
  Files,
  Folder,
  FileCode,
  FilePlus,
  Code,
  GitBranch,
  Bug,
  Package,
  Wrench,
  Cpu,
  Database,
  Search,
  Table,
  Calculator,
  Image,
  Film,
  Music,
  Download,
  Upload,
  Link as LinkIcon,
  Send,
  Mail,
  MessageSquare,
  Calendar,
  MapPin,
  Book,
  Shield,
  Bell,
  Star,
  Key,
  Lock,
  ListChecks,
  Plug,
  CloudSun,
  HardDrive,
  Network,
  Rocket,
} from 'lucide-vue-next'

// 图标名（小写短横线）→ 组件
export const TOOL_ICON_MAP = {
  zap: Zap,
  terminal: Terminal,
  'square-terminal': SquareTerminal,
  blocks: Blocks,
  puzzle: Puzzle,
  webhook: Webhook,
  globe: Globe,
  cloud: Cloud,
  'cloud-sun': CloudSun,
  bot: Bot,
  'file-text': FileText,
  files: Files,
  folder: Folder,
  'file-code': FileCode,
  'file-plus': FilePlus,
  code: Code,
  'git-branch': GitBranch,
  bug: Bug,
  package: Package,
  wrench: Wrench,
  cpu: Cpu,
  database: Database,
  search: Search,
  table: Table,
  calculator: Calculator,
  image: Image,
  film: Film,
  music: Music,
  download: Download,
  upload: Upload,
  link: LinkIcon,
  send: Send,
  mail: Mail,
  'message-square': MessageSquare,
  calendar: Calendar,
  'map-pin': MapPin,
  book: Book,
  shield: Shield,
  bell: Bell,
  star: Star,
  key: Key,
  lock: Lock,
  'list-checks': ListChecks,
  plug: Plug,
  'hard-drive': HardDrive,
  network: Network,
  rocket: Rocket,
}

/** 可选图标名列表（图标选择器遍历用） */
export const TOOL_ICON_NAMES = Object.keys(TOOL_ICON_MAP)
