// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1) {
  return window['go']['main']['App']['AddModel'](arg1);
}

export function AppendConversation(arg1, arg2) {
  return window['go']['main']['App']['AppendConversation'](arg1, arg2);
}

export function AppendMessage(arg1, arg2) {
  return window['go']['main']['App']['AppendMessage'](arg1, arg2);
}

export function Chat(arg1, arg2) {
  return window['go']['main']['App']['Chat'](arg1, arg2);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function GetDiffTurns(arg1) {
  return window['go']['main']['App']['GetDiffTurns'](arg1);
}

export function GetModel(arg1) {
  return window['go']['main']['App']['GetModel'](arg1);
}

export function GetModelNames() {
  return window['go']['main']['App']['GetModelNames']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function UpdateSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateSession'](arg1, arg2);
}
